version: "3.9"
services:
    sms-proxy:
        build: .
        ports:
            - "3030:80"
        volumes:
            - ./sms_proxy.py:/sms_proxy.py
            - ./.env:/.env
        restart: unless-stopped
        networks:
          - sms-proxy-network

networks:
  sms-proxy-network:
